--ozone-platform-hint=auto
--ozone-platform=wayland
--enable-features=WaylandWindowDecorations
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-hardware-overlays
--enable-features=VaapiVideoDecodeLinuxGL
--use-gl=egl
--enable-smooth-scrolling
--enable-features=ImpulseScrollAnimations,PercentBasedScrolling
