# === WORKSPACES ===

windowrule = match:class ^(google-chrome)$, workspace 1
windowrule = match:class ^(code-oss)$, workspace 2
windowrule = match:class ^(steam)$, workspace 4
windowrule = match:class ^(org.telegram.desktop)$, workspace 6

# === FLOAT ===

windowrule = match:class ^(pavucontrol)$, float 1
windowrule = match:class ^(pavucontrol)$, center 1
windowrule = match:class ^(pavucontrol)$, size 900 600

windowrule = match:class ^(qalculate-gtk)$, float 1
windowrule = match:class ^(qalculate-gtk)$, center 1

# === PIP ===

windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, pin 1
windowrule = match:title ^(Picture-in-Picture)$, size 25% 25%

windowrule = match:class ^(gamescope)$, immediate 1

windowrule = match:class ^(org.telegram.desktop)$, float 1
windowrule = match:class ^(org.telegram.desktop)$, size 430 920
windowrule = match:class ^(org.telegram.desktop)$, center 1
windowrule = match:class ^(org.telegram.desktop)$, opacity 0.97
