# === WORKSPACES ===

windowrule = match:class ^(google-chrome)$, workspace 1
#windowrule = match:class ^(code-oss)$, workspace 2
windowrule = match:class ^(steam)$, workspace 4
windowrule = match:class ^(org.telegram.desktop)$, workspace 6
#windowrule = match:class ^(app.hiddify.com)$, workspace 5

# === FLOAT ===

windowrule = match:class ^(pavucontrol)$, float 1
windowrule = match:class ^(pavucontrol)$, center 1
windowrule = match:class ^(pavucontrol)$, size 900 600

windowrule = match:class ^(qalculate-gtk)$, float 1
windowrule = match:class ^(qalculate-gtk)$, center 1

# === PIP ===

windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, pin 1
windowrule = match:title ^(Picture-in-Picture)$, size 25% 25%

windowrule = match:class ^(gamescope)$, immediate 1

windowrule = match:class ^(org.telegram.desktop)$, float 1
windowrule = match:class ^(org.telegram.desktop)$, size 430 920
windowrule = match:class ^(org.telegram.desktop)$, center 1
windowrule = match:class ^(org.telegram.desktop)$, opacity 0.97

windowrule = match:class ^(app.hiddify.com)$, float 1
windowrule = match:class ^(app.hiddify.com)$, size 430 920

windowrule = no_blur on, match:class ^(gamescope)$
windowrule = no_anim on, match:class ^(gamescope)$

windowrule = no_blur on, match:fullscreen 1
windowrule = no_anim on, match:fullscreen 1

windowrule = float 1, match:class ^(steam)$
windowrule = size 450 400, match:class ^(steam)$
windowrule = center 1, match:class ^(steam)$

windowrule = fullscreen 1, match:class ^(run\.exe)$
windowrule = size 100% 100%, match:class ^(run\.exe)$
windowrule = move 0 0, match:class ^(run\.exe)$

windowrule = float 1, match:class ^(waypaper)$
windowrule = size 500 600, match:class ^(waypaper)$

windowrule = no_anim on, match:class ^(google-chrome)$
windowrule = immediate on, match:class ^(google-chrome)$


